#!/usr/bin/env bash
# Update NGINX config, disable IPv6, and restart
sed -i -e 's/listen 8080;/listen 80/g' -e 's/ listen 8080;/ listen 80/g' -e 's/ ipv6only=on//' /etc/nginx/sites-available/default
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
