#!/usr/bin/env bash
# print the 23 hrs 59 mins
hours=0
minutes=1

while [[ $hours -lt 13 ]]; do
	if [[ hours -gt 1 ]]; then
		echo "Hours: $hours"
	else
		echo "Hour: $hours"
	fi
	while [[ $minutes -lt 60 ]]; do
		echo $minutes
		minutes=$((minutes + 1))
	done
	minutes=1
	hours=$((hours + 1))
done
