#!/usr/bin/env bash
# Sets up nginx user
# Check if sudo is available; if not, install it
if ! command -v sudo &> /dev/null; then
  apk add --no-cache sudo
fi

# Check if the nginx user exists; if not, create it
if ! id -u nginx &> /dev/null; then
  adduser -D -H -s /sbin/nologin nginx
fi

# Change the user in the nginx configuration file if not already commented
if ! grep -qE "^\s*#.*user\s+nginx;" /etc/nginx/nginx.conf; then
  sed -i 's/^\s*user\s*nginx;/#user nginx;/' /etc/nginx/nginx.conf
fi

# Modify the Nginx configuration to listen on port 8080 if not already commented
if ! grep -qE "^\s*#.*listen\s+80;" /etc/nginx/conf.d/default.conf; then
  sed -i 's/^\s*listen\s*80;/#listen 8080 default_server;/' /etc/nginx/conf.d/default.conf
fi

# Restart Nginx to apply the changes
service nginx restart

# Verify that Nginx is running as the nginx user
ps aux | grep nginx

# Check if Nginx is listening on port 8080
nc -z -v -w 1 localhost 8080
