#!/usr/bin/env bash
# creates an RSA key pair called school
# with 4096 bits and protected by the passphrase
# called betty

KEY_NAME = "school"
PASSPHRASE = "betty"
BITS = 4096

ssh-keygen -t rsa -b $BITS -f "$KEY_NAME" -N "$PASSPHRASE"
