#!/usr/bin/env bash
# creates an RSA key pair called school
# with 4096 bits and protected by the passphrase
# called betty

KEY_NAME = "school"
PASSPHRASE = "betty"
BITS = 4096

ssh-keygen -t rsa -b $BITS -f "$KEY_NAME" -N "$PASSPHRASE"

# Display the key information
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $KEY_NAME."
echo "Your public key has been saved in $KEY_NAME.pub."
echo "The key fingerprint is:"
ssh-keygen -l -f "$KEY_NAME"
echo "The key's randomart image is:"
ssh-keygen -l -v -f "$KEY_NAME"
