#!/usr/bin/env bash

echo "Host *" >> ~/.ssh/config
echo "    IdentityFile ~/.ssh/school" >> ~/.ssh/config
echo "    PasswordAuthentication no" >> ~/.ssh/config

echo "SSH client configuration updated."
